# Generated by Django 2.2.11 on 2020-03-27 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('privacy_policy_filename', models.CharField(default='', max_length=256)),
                ('terms_and_conditions_filename', models.CharField(default='', max_length=256)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'privacy_policy_filename', 'terms_and_conditions_filename')},
            },
        ),
    ]
