# Generated by Django 2.2.11 on 2020-03-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='privacy_policy_filename',
            field=models.CharField(default='privacy_policy_06_26_2020.pdf', max_length=256),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='terms_and_conditions_filename',
            field=models.CharField(default='terms_&_conditions_06_26_2020.pdf', max_length=256),
        ),
    ]
