#!/usr/bin/env python3
import sys

def main():

    try:
        options_file = sys.argv[1]
    except IndexError:
        options_file = "/service/config/jvm.options"

    options = []
    try:
        with open(options_file, "r") as fp:
            for line in fp.readlines():
                line = line.strip()
                if line.startswith("#") or not line:
                    continue
                options.append(line)
    except Exception as e:
        options = [
            "-Xms512m",
            "-Xmx1g"
        ]

    print(" ".join(options))

if __name__ == "__main__":
    main()
