# Generated by Django 3.2 on 2021-05-12 22:57

from django.db import migrations, models
from django.db.migrations import RunPython


def set_trigger_order(apps, schema_editor):
    Trigger = apps.get_model("webhooks", "Trigger")
    for name, sort_index in [('AssetAnalyzed', 10), ('AssetModified', 20)]:
        trigger = Trigger.objects.get(name=name)
        trigger.sort_index = sort_index
        trigger.save()


class Migration(migrations.Migration):

    dependencies = [
        ('webhooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trigger',
            options={'ordering': ['sort_index']},
        ),
        migrations.AddField(
            model_name='trigger',
            name='sort_index',
            field=models.IntegerField(default=10),
        ),
        RunPython(set_trigger_order)
    ]
