# Generated by Django 3.0.8 on 2020-08-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userregistrationtoken',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
