#!/usr/bin/env python
import sys

def main():

    try:
        options_file = sys.argv[1]
    except IndexError:
        options_file = "/config/jvm.options"

    options = []
    try:
        with open(options_file, "r") as fp:
            for line in fp.readlines():
                line = line.strip()
                if line.startswith("#") or not line:
                    continue
                options.append(line)
    except Exception, e:
        options = [
            "-Xms512m",
            "-Xmx1g",
            "-Xss1m"
        ]

    print " ".join(options)

if __name__ == "__main__":
    main()
