{
 "title": "Zorroa Job System",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Task Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(zorroa_task_errors_total[1m])",
     "legendFormat": "{{processor}}"
    }
   ]
  },
  {
   "title": "Task States",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Changes/Sec" }
   ],
   "targets": [
    {
     "expr": "rate(zorroa_task_state_total[1m])",
     "legendFormat": "{{task_state}}"
    },
    {}
   ]
  },
  {
   "title": "Asset Indexing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Index/Sec" }
   ],
   "targets": [
    {
     "expr": "rate(zorroa_asset_index_total[1m])",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}