#!/usr/bin/env python3
import sys
import os

def main():

    try:
        options_file = sys.argv[1]
    except IndexError:
        options_file = "/service/jvm.options"

    # Override everything with ENV var.
    java_opts = os.environ.get("JAVA_OPTS")
    if java_opts:
        print(java_opts)
        return

    options = [
        "-Xms{}".format(os.environ.get("JVM_MIN_HEAP", "512m")),
        "-XX:MaxRAMPercentage={}".format(os.environ.get("JVM_MAX_HEAP_PERC", "55"))
    ]

    try:
        with open(options_file, "r") as fp:
            for line in fp.readlines():
                line = line.strip()
                if line.startswith("#") or not line:
                    continue
                options.append(line)
    except Exception as e:
        return options

    print(" ".join(options))

if __name__ == "__main__":
    main()
