# Generated by Django 2.2.7 on 2019-12-04 20:06

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='apikey',
            field=django_cryptography.fields.encrypt(models.TextField()),
        ),
    ]
