# Generated by Django 3.0.7 on 2020-07-02 21:46

import logging

from django.db import migrations
from zmlp.client import ZmlpNotFoundException

from projects.models import Membership
from wallet.utils import convert_base64_to_json

logger = logging.getLogger(__name__)


def recreate_membership_api_keys(apps, schema_editor):
    for membership in Membership.objects.all():
        try:
            membership.sync_with_zmlp(force=True)
        except ValueError:
            logger.warning('Skipping recreating the admin-key. Please manually verify.')
            continue
        except IOError as e:
            logger.warning(f'Had an issue cleaning up an apikey, please check: {str(e)}')
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200528_2041'),
        ('subscriptions', '0002_auto_20200528_2041'),
        ('wallet', '0004_remove_system_permissions_from_users'),
    ]

    operations = [
        migrations.RunPython(recreate_membership_api_keys)
    ]
