# Generated by Django 3.0.7 on 2020-07-02 21:46

from django.db import migrations
from zmlp.client import ZmlpNotFoundException

from projects.models import Membership
from wallet.utils import convert_base64_to_json


def recreate_membership_api_keys(apps, schema_editor):
    for membership in Membership.objects.all():
        client = membership.project.get_zmlp_super_client()
        _id = convert_base64_to_json(membership.apikey).get('id')
        if _id:
            try:
                client.delete(f'/auth/v1/apikey/{_id}')
            except ZmlpNotFoundException:
                pass
        membership.apikey = ''
        membership.sync_with_zmlp(client)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200528_2041'),
    ]

    operations = [
        migrations.RunPython(recreate_membership_api_keys)
    ]
