# Generated by Django 2.2.10 on 2020-02-25 02:13

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200129_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='apikey',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
    ]
