# Generated by Django 3.1.5 on 2021-01-11 22:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200810_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='modifiedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
