# Generated by Django 2.2.11 on 2020-03-18 23:56

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200225_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ML_Tools', 'ML Tools'), ('API_Keys', 'API Keys'), ('User_Admin', 'User Admin')], max_length=28),
        ),
    ]
