# Generated by Django 2.2.12 on 2020-04-28 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_membership_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
