# Generated by Django 3.1.7 on 2021-03-17 20:28

from django.db import migrations, models
import django_cryptography.fields

from projects.models import Project


def sync_project_with_zmlp(apps, schema_editor):
    for project in Project.objects.all():
        project.sync_with_zmlp()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20210128_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='apikey',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True, editable=False, null=True)),
        ),
        migrations.RunPython(sync_project_with_zmlp)
    ]
