# Generated by Django 3.1.7 on 2021-04-06 00:28

from django.db import migrations, models
import django.db.models.deletion


def create_default_boon_organization(apps, schema_editor):
    """Creates a Boon AI organization and adds all orphaned projects to it."""
    Organization = apps.get_model('organizations', 'Organization')
    Project = apps.get_model('projects', 'Project')
    boon_org, created = Organization.all_objects.get_or_create(name='Boon AI')
    for project in Project.all_objects.filter(organization__isnull=True):
        project.organization = boon_org
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20210317_2308'),
        ('projects', '0009_auto_20210331_2321'),
    ]

    operations = [
        migrations.RunPython(create_default_boon_organization),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='organizations.organization'),
        ),
    ]
