# Generated by Django 3.1.7 on 2021-04-10 01:46

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210406_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='roles',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('ML_Tools', 'ML Tools'), ('API_Keys', 'API Keys'), ('User_Admin', 'User Admin'), ('Webhooks', 'Webhooks')], max_length=37),
        ),
    ]
