# Generated by Django 2.2.12 on 2020-05-20 18:14

from django.contrib.auth.models import User
from django.db import migrations
from django.conf import settings


def forwards(apps, schema_editor):
    User.objects.create_superuser(username=settings.SUPERUSER_EMAIL, email=settings.SUPERUSER_EMAIL,
                                  password=settings.SUPERUSER_PASSWORD, first_name='Admin',
                                  last_name='Adminson')


def reverse(apps, schema_editor):
    User.objects.get(username=settings.SUPERUSER_EMAIL).delete()


class Migration(migrations.Migration):

    dependencies = []

    operations = [migrations.RunPython(forwards, reverse)]
