# Generated by Django 3.0.6 on 2020-06-25 18:55
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations

from projects.models import Project

User = get_user_model()


def sync_project_with_zmlp(apps, schema_editor):
    for project in Project.objects.all():
        project.sync_with_zmlp()


def fake_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('wallet', '0002_data_migration_add_project_zero'),
    ]

    operations = [
        migrations.RunPython(sync_project_with_zmlp, fake_reverse)
    ]
