# Generated by Django 3.0.7 on 2020-07-01 20:06

import logging

from django.contrib.auth import get_user_model
from django.db import migrations
from wallet.utils import get_zmlp_superuser_client

User = get_user_model()
logger = logging.getLogger(__name__)


def recreate_user_memberships(apps, schema_editor):
    for user in User.objects.all():
        for membership in user.memberships.all():
            superuser_client = get_zmlp_superuser_client(membership.project.id)
            membership.sync_with_zmlp(superuser_client)
            logger.info(f'Cycled apikey for {user.username} on project '
                        f'{membership.project.name}')


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_sync_zmlp_projects'),
    ]

    operations = [
        migrations.RunPython(recreate_user_memberships)
    ]
