# Generated by Django 3.0.7 on 2020-07-01 20:06

import logging

from django.contrib.auth import get_user_model
from django.db import migrations

User = get_user_model()
logger = logging.getLogger(__name__)


def recreate_user_memberships(apps, schema_editor):
    # This migration was no good.
    return


def fake_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_sync_zmlp_projects'),
    ]

    operations = [
        migrations.RunPython(recreate_user_memberships, fake_reverse)
    ]
