# Generated by Django 3.0.11 on 2020-12-09 19:24

import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def upgrade_subscription(apps, schema_editor):
    # This migration is no longer necessary after removing subscription. Not removing it
    # to keep the migration chain intact in production.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_system_permissions_from_users'),
    ]

    operations = [
        migrations.RunPython(upgrade_subscription)
    ]
