# Generated by Django 3.2.2 on 2021-06-08 21:19

from django.db import migrations

from wallet.utils import sync_membership_with_zmlp


def CycleMembershipApiKeys(apps, schema_editor):
    Membership = apps.get_model('projects', 'Membership')
    for membership in Membership.objects.all():
        sync_membership_with_zmlp(membership)


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_project_zero_premier_subscription'),
    ]

    operations = [
        migrations.RunPython(CycleMembershipApiKeys)
    ]
