# Generated by Django 3.2.2 on 2021-06-08 22:57

from django.db import migrations

from projects.models import Project


def cycle_project_api_keys(apps, schema):
    for project in Project.all_objects.all():
        project.cycle_api_key()


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_sync_zmlp_memberships'),
    ]

    operations = [
        migrations.RunPython(cycle_project_api_keys)
    ]
