{
 "title": "Archivist REST API Metrics",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   { "name": "status", "label": "HTTP Response Code", "query": "label_values(outcome)" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Requests per minute",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 11, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count[1m]))"
    }
   ]
  },
  {
   "title": "2XX Responses per min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{outcome=\"SUCCESS\"}[1m])) "
    }
   ]
  },
  {
   "title": "4XX Responses per min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{outcome=\"CLIENT_ERROR\"}[1m]))"
    }
   ]
  },
  {
   "title": "5XX Responses per min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count{outcome=\"SERVER_ERROR\"}[1m]))"
    }
   ]
  },
  {
   "title": "API HTTP Status Codes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(http_server_requests_seconds_count[1m])) by (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "API Request Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 2 },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "quantile=50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "quantile=95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "quantile=99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(http_server_requests_seconds_bucket[1m])) by (le))",
     "legendFormat": "quantile=99.9"
    }
   ]
  },
  {
   "title": "HTTP responses by URI",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{outcome=~\"$status\"}"
    }
   ]
  }
 ]
}