/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.zorroa.cluster.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-01-21")
public class TaskStopT implements org.apache.thrift.TBase<TaskStopT, TaskStopT._Fields>, java.io.Serializable, Cloneable, Comparable<TaskStopT> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TaskStopT");

  private static final org.apache.thrift.protocol.TField EXIT_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("exitStatus", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TaskStopTStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TaskStopTTupleSchemeFactory();

  public int exitStatus; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    EXIT_STATUS((short)1, "exitStatus");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // EXIT_STATUS
          return EXIT_STATUS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __EXITSTATUS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.EXIT_STATUS, new org.apache.thrift.meta_data.FieldMetaData("exitStatus", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TaskStopT.class, metaDataMap);
  }

  public TaskStopT() {
  }

  public TaskStopT(
    int exitStatus)
  {
    this();
    this.exitStatus = exitStatus;
    setExitStatusIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TaskStopT(TaskStopT other) {
    __isset_bitfield = other.__isset_bitfield;
    this.exitStatus = other.exitStatus;
  }

  public TaskStopT deepCopy() {
    return new TaskStopT(this);
  }

  @Override
  public void clear() {
    setExitStatusIsSet(false);
    this.exitStatus = 0;
  }

  public int getExitStatus() {
    return this.exitStatus;
  }

  public TaskStopT setExitStatus(int exitStatus) {
    this.exitStatus = exitStatus;
    setExitStatusIsSet(true);
    return this;
  }

  public void unsetExitStatus() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXITSTATUS_ISSET_ID);
  }

  /** Returns true if field exitStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetExitStatus() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXITSTATUS_ISSET_ID);
  }

  public void setExitStatusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXITSTATUS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, java.lang.Object value) {
    switch (field) {
    case EXIT_STATUS:
      if (value == null) {
        unsetExitStatus();
      } else {
        setExitStatus((java.lang.Integer)value);
      }
      break;

    }
  }

  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case EXIT_STATUS:
      return getExitStatus();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case EXIT_STATUS:
      return isSetExitStatus();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that == null)
      return false;
    if (that instanceof TaskStopT)
      return this.equals((TaskStopT)that);
    return false;
  }

  public boolean equals(TaskStopT that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_exitStatus = true;
    boolean that_present_exitStatus = true;
    if (this_present_exitStatus || that_present_exitStatus) {
      if (!(this_present_exitStatus && that_present_exitStatus))
        return false;
      if (this.exitStatus != that.exitStatus)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + exitStatus;

    return hashCode;
  }

  @Override
  public int compareTo(TaskStopT other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.valueOf(isSetExitStatus()).compareTo(other.isSetExitStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExitStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.exitStatus, other.exitStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TaskStopT(");
    boolean first = true;

    sb.append("exitStatus:");
    sb.append(this.exitStatus);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TaskStopTStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TaskStopTStandardScheme getScheme() {
      return new TaskStopTStandardScheme();
    }
  }

  private static class TaskStopTStandardScheme extends org.apache.thrift.scheme.StandardScheme<TaskStopT> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, TaskStopT struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // EXIT_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.exitStatus = iprot.readI32();
              struct.setExitStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, TaskStopT struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(EXIT_STATUS_FIELD_DESC);
      oprot.writeI32(struct.exitStatus);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TaskStopTTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public TaskStopTTupleScheme getScheme() {
      return new TaskStopTTupleScheme();
    }
  }

  private static class TaskStopTTupleScheme extends org.apache.thrift.scheme.TupleScheme<TaskStopT> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TaskStopT struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetExitStatus()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetExitStatus()) {
        oprot.writeI32(struct.exitStatus);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TaskStopT struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.exitStatus = iprot.readI32();
        struct.setExitStatusIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

