ALTER TABLE job ADD json_args TEXT NOT NULL DEFAULT '{}';

ALTER TABLE job DROP COLUMN json_script;
ALTER TABLE job ADD json_env TEXT NOT NULL DEFAULT '{}';
ALTER TABLE task ADD str_name VARCHAR(128) NOT NULL;
