
ALTER TABLE taxonomy ADD COLUMN bool_active BOOLEAN DEFAULT 0 NOT NULL;
ALTER TABLE taxonomy ADD COLUMN time_started BIGINT DEFAULT 0 NOT NULL;
ALTER TABLE taxonomy ADD COLUMN time_stopped BIGINT DEFAULT 0 NOT NULL;
