# Generated by Django 3.1.5 on 2021-01-28 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210128_0017'),
        ('gcpmarketplace', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketplaceentitlement',
            name='project',
        ),
        migrations.AddField(
            model_name='marketplaceentitlement',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_entitlement', to='organizations.organization'),
        ),
    ]
