#!/usr/bin/env python
import zorroa.zsdk
from zplugins.classifiers.processors import NeuralNetClassifierProcessor
from zorroa.zsdk.testing import PluginUnitTestCase


class ClassifiersUnitTests(PluginUnitTestCase):
    @classmethod
    def setUpClass(cls):
        super(ClassifiersUnitTests, cls).setUpClass()

    def setUp(self):
        self.frame = zorroa.zsdk.Frame(zorroa.zsdk.Document(data={'id': '9f0f8a1d-4719-5cf8-b427-4612c5597811'}))
        self.frame.asset.set_attr(
            'analysis.imageSimilarity.shash',
            '0050FPPOGPPKPIPCAPPPDHHIGPCLJEPLPPPAPPGPDPFPPGPADCBFGIPGDDCIPIGPPDPABPOMPNPAPBPPDKP' +
            'MPJMAPBPDPBOGLPDPPADOENPAAPBPPAPGAIGPDIPOGEPLCGAPPPPOAPBAJFMPPPDCPNKGAAMPLHIPEPDICO' +
            'PLPIAEPACLJPCKMPGBPOLJAABLAPAPMMPOFPKPHEPLBPPMLPKFNPMKACECLPJPPABPPPAFPGIOEPBPAPPOH' +
            'AFAHPPPJPPMDPAPPPELPAPCPPAKMLHJGPAGPMKPALPJPOMPPPPPJPPPAPPPLFINKPEBAAPADDPNMPLPPCBD' +
            'PPOCCBCIPHDACPPCPHBDPBAPBPPALAPHPCFBCADAAPPHPHEPNHNCBOPDPPIPEABNHFPAPEPPDPPAAAPLMDP' +
            'EAKPPPEGPAFPPBABDAOCKPPNPOPPGBGGPPKPMBPCDKCPBCDAPAPACAPPKHPGPPPPANPCEPCPJJGPPPEAPPA' +
            'LPAIPEIICAGPPEPDDPNPFACMPGPBPDCFICPAPPPPCPCPNIGPBPNAGPPJEPEPPAHPAEAMKPBMLAPHPNPPDAK' +
            'PGCPGPPPPPPABABPCPPANPPDEPHGCKFPAPPAPOEHNAAAKPDPNPOAGOPBPPPAPIPPIDDAPPPMAAPEMAIGAKG' +
            'ABPPPGLPAPDOEHKIPPHPNPJCNPAGECLIIFAKPDIGDAPNPDPPIGACAOPACPBPBCAPPKPPIMPFKAALPAPGBAK' +
            'AKPJPKDOAPPBPPPPPHIAPPBPPPPBFPPABACPGDJIPBPLIHPHPLPPIPLAPBCOGOJPGAPAGPDPMAMCNLGLHIL' +
            'PMGDPAMAPJPHPPLPDFBDAKPLPPPKOPPGIFCPDJJPOPAPNAADAGPLGAEPMAFOPEPAHIDPDPBAJMEOGAPCGCA' +
            'MPNCJFDPPGGDCMJPHMDPLGDAMIACPPPPPKPPIGPPPPOACPADPFPKBPNPCHPHBFAPONFKAEAPADPACAMLPPI' +
            'PPDMPCPAPBCPCPJPJFFHPPCPGMPPFHPAMEAOIPPPDPPMAPJAHPPPPPCPAFPAAPEMAAMPPPBBAPDPLHDPPPB' +
            'PPGHEEPDPDPPPEFGPBPBFEPLEPAAPEAPPEMAPPGJLGPPADNPPFMDPMFMPNPAOBMPAAICPGNPPJPPPDOPDBP' +
            'ADAPHPPDAAAEHAPCPIAKLPGAHLPHDBABPHGPKBNFPPGPADPKEFPEEMPDJBIPAPBPCPBHPPCIODDAPLGPBDP' +
            'APKBIPNBCIFHMDPAHPPPPCPPHABAAGPCPAACKFLJPPBAPPMPMOPAACJEPGPBEEHPPGPHPPIAPMPBEBPJBBF' +
            'BPKPPHPPAPDECPPOBIPPIPBAAAPABGABPAPGGJJPAEEPBPABDEBPPODCPGDPKPPPAPPJDBKPOPABPPAIGGG' +
            'PCBDPJBBPPAPPAPADEPPAPAPPFPPPPPPPCDPPLDIDBNPOECGPJPGLPPACPEPPPPPFFAPPBPCAMPKGPAGOPP' +
            'PPGAAFPAPPLPEPHPKBAEJPPBDPPDPPIGOGPFPKBLMBPPAHPIJPLEAIHPPPBFBOEADBPFCDPPGAAPMKPNPCP' +
            'MAPJPHEOPPIKEEOJPKEDJIEAIJPPPBNPEPPJJADFCKMCPADABEABPAPPAOBKDEIPAACPPDBEPPFPDCJPPCP' +
            'CIABPAPHHPCLPMPNPPJAPNALPGKPOPAGPICGPGPAPPCPDPPGAFADLHIPPPOPPKPPAELAMLKACPIPPJBPBPA' +
            'PCCAPHPPJPFPBKBPHGKDAPPPBAPHDAPMBPOABEPPPPHJNPAEPELCPPPPPPCCAJPBPNFGADHPPIKHGGBPAKF' +
            'APODJCPPPPGCPPPPPPKAAAPKBNPPIHOPKPOHPPPAHJABEPKABGPGGDEAMPAAMFELPHILIPAPEHEPPPPPPLC' +
            'APAPPPJPPIPBDGJPCBPKEGCHPJGJPPKPPPFBAPAFDHPFPEDHPLMPBJAPNPBAJBPAJEPJEAGPPFFPJFPLPIP' +
            'JJEPPJPPEMGLKAAPPDCEPPLAGCEIEMAFPABPIPKPPPBAPKOPJAAKPABDFDCFB')

    def test_NeuralNetClassifier_defaults(self):
        processor = self.init_processor(NeuralNetClassifierProcessor(), {"model": "ClassifierTest"})
        processor.process(self.frame)
        self.assertEquals("sunny_right",
                          self.frame.asset.get_attr("analysis")["imageClassify"]["pred0"])
