# Generated by Django 2.2.12 on 2020-05-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('logo_data_uri', models.TextField(help_text='Paste in the base64 data uri text string of an image. You can use https://www.base64-image.de/ to convert images, use the "copy image" button after converting and paste results above. If you have an svg you can use https://base64.guru/converter/encode/image/svg')),
            ],
        ),
    ]
