# Generated by Django 3.1.5 on 2021-02-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0005_change_zorroa_to_boon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ['sort_index']},
        ),
        migrations.AddField(
            model_name='provider',
            name='sort_index',
            field=models.IntegerField(default=10),
        ),
    ]
