# Generated by Django 3.1.5 on 2021-02-20 00:26

from django.db import migrations


def set_sort_order(apps, schema_editor):
    Provider = apps.get_model('modules', 'Provider')

    order_map = {'boon ai': 1,
                 'google': 2,
                 'amazon': 3,
                 'microsoft': 4,
                 'clarifai': 5}
    all_providers = Provider.objects.all()
    for provider in all_providers:
        if provider.name in order_map:
            provider.sort_index = order_map[provider.name]
            provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0006_provider_sort_index_ordering'),
    ]

    operations = [
        migrations.RunPython(set_sort_order)
    ]
