# Generated by Django 3.1.5 on 2021-03-08 23:26

from django.db import migrations


def forwards(apps, schema_editor):
    descriptions = {'boon ai': 'Choose from these BoonAI propriety analysis modules. They are billed as internal modules.',  # noqa
                    'google': 'Choose from these Google Cloud Vision API analysis modules. They are billed as external modules.',  # noqa
                    'amazon': 'Choose from these Amazon Machine Learning Services analysis modules. They are billed as external modules.',  # noqa
                    'microsoft': 'Choose from these Microsoft Azure Machine Learning analysis modules. They are billed as external modules.',  # noqa
                    'clarifai': 'Choose from these Clarifai Computer Vision analysis modules. They are billed as external modules.'}  # noqa
    Provider = apps.get_model('modules', 'Provider')
    for name, description in descriptions.items():
        provider = Provider.objects.get(name=name)
        provider.description = description
        provider.save()


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0007_data_migration_set_provider_order'),
    ]

    operations = [
        migrations.RunPython(forwards)
    ]
