#!/usr/bin/env python3
import os
import subprocess
import sys
from time import sleep

from google.cloud import monitoring_v3
from kubernetes import client, config
from boonsdk import BoonClient

from lib.metrics import JobQueueMetrics

REGISTERED_METRICS = (JobQueueMetrics,)


class Reporter:
    """Publishes metrics to the GCP Monitoring service. For information about the arguments
    for this class and how to configure it please view the README.md.

    Args:
        project_id(str): GCP project id to publish metrics to.
        interval(int): Interval, in seconds, metrics are published on.
        zmlp_api_url(str): FQDN to the ZMLP API.
        inception_key_b64(str): Inception key for the ZMLP API used to get info from ZMLP.

    """
    def __init__(self, project_id=None, interval=None, zmlp_api_url=None, inception_key_b64=None):
        self.project_id = project_id or os.getenv('PROJECT_ID', 'zvi-dev')
        self.interval = int(interval or os.getenv('COLLECTION_INTERVAL', 30))
        zmlp_api_url = zmlp_api_url or os.getenv('BOONAI_API_URL', 'https://dev.api.zvi.zorroa.com')
        inception_key_b64 = inception_key_b64 or os.getenv('INCEPTION_KEY_B64')

        self.monitoring_client = monitoring_v3.MetricServiceClient()
        self.zmlp_client = BoonClient(apikey=inception_key_b64, server=zmlp_api_url)
        self.k8s_client = self._configure_k8s_client()

    def monitor(self):
        """Loops and collects and reports the registered statistics."""
        try:
            while True:
                print('Starting a round of metric collection:')
                self.publish()
                print(f'Completed current round of metric collection. Sleeping for {self.interval} seconds.')
                sleep(self.interval)
        except KeyboardInterrupt:
            print('Terminated by User, Metric Reporter exiting.')
            sys.exit(1)

    def publish(self):
        """Publishes all of the registered metrics."""
        for Metric in REGISTERED_METRICS:
            metric = Metric(self.monitoring_client, self.zmlp_client, self.k8s_client,
                            self.project_id)
            metric.publish()

    def _configure_k8s_client(self):
        subprocess.check_call(['gcloud', 'container', 'clusters', 'get-credentials', 'zmlp',
                               '--zone', 'us-central1-a', '--project', self.project_id])
        config.load_kube_config()
        return client


def main():
    reporter = Reporter()
    reporter.monitor()


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('Interrupted, exiting.')
        sys.exit(1)

