# Generated by Django 2.2.11 on 2020-04-05 09:49

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import wallet.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0006_membership_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('search', wallet.fields.JSONField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
            options={
                'verbose_name_plural': 'Searches',
            },
        ),
    ]
