# Generated by Django 3.0.8 on 2020-08-10 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searches', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='created_by',
            new_name='createdBy',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='created_date',
            new_name='createdDate',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='modified_date',
            new_name='modifiedDate',
        ),
    ]
