#!/usr/bin/python3

import argparse
import json

def main():

    parser = argparse.ArgumentParser(prog='set_attr')
    parser.add_argument("-i", "--input-file", help="The docker image to execute")
    parser.add_argument("-a", "--args", help="The docker image to execute")

    args = parser.parse_args()

    obj = {}
    if args.input_file:
        with open(args.input_file, "r") as fp:
            obj = json.load(fp)

    if args.args:
        zargs = json.loads(args.args)
        for k,v in zargs.items():
            obj[k] = v   

    event = {"type": "object", "payload": obj}

    print("####HEADER####")
    print(json.dumps(event))
    print("####FOOTER####")


if __name__ == '__main__':
    main()

