from .automl import AutoMLModelProcessor
from .cloud_vision import CloudVisionProcessor
from .cloud_video import CloudVideoIntelligenceProcessor
from .cloud_lang import CloudNaturalLanguageProcessor
from .cloud_speech import CloudSpeechToTextProcessor
