# Generated by Django 3.0.6 on 2020-05-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='image_count_limit',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='modules',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='video_hours_limit',
        ),
        migrations.AddField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('essentials', 'Essentials'), ('premier', 'Premier')], default='essentials', max_length=20),
        ),
    ]
