# Generated by Django 3.1.5 on 2021-01-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210115_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
