# Generated by Django 3.1.5 on 2021-01-28 00:17

from django.db import migrations, models
import django.db.models.manager
import organizations.utils


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='organization',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('access', 'Access'), ('build', 'Build'), ('custom_enterprise', 'Custom Enterprise')], default='access', max_length=24),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(default=organizations.utils.random_organization_name, max_length=144, unique=True),
        ),
    ]
