# Generated by Django 3.1.7 on 2021-03-17 23:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0003_auto_20210317_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='owners',
            field=models.ManyToManyField(related_name='organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
