const aggregate = {
  count: 604,
  results: {
    docCountErrorUpperBound: 0,
    sumOtherDocCount: 0,
    buckets: [
      { key: 'web_site', docCount: 134 },
      { key: 'alp', docCount: 75 },
      { key: 'sports_car', docCount: 56 },
      { key: 'menu', docCount: 45 },
      { key: 'convertible', docCount: 27 },
      { key: 'racer', docCount: 27 },
      { key: 'valley', docCount: 26 },
      { key: 'cab', docCount: 23 },
      { key: 'envelope', docCount: 23 },
      { key: 'tabby', docCount: 22 },
      { key: 'minivan', docCount: 20 },
      { key: 'beach_wagon', docCount: 17 },
      { key: 'volcano', docCount: 16 },
      { key: 'Egyptian_cat', docCount: 14 },
      { key: 'tiger_cat', docCount: 13 },
      { key: 'grille', docCount: 11 },
      { key: 'Model_T', docCount: 10 },
      { key: 'pickup', docCount: 10 },
      { key: 'fire_engine', docCount: 9 },
      { key: 'car_wheel', docCount: 8 },
      { key: 'tow_truck', docCount: 7 },
      { key: 'jeep', docCount: 6 },
      { key: 'book_jacket', docCount: 5 },
      { key: 'Siamese_cat', docCount: 4 },
      { key: 'pillow', docCount: 4 },
      { key: 'Band_Aid', docCount: 3 },
      { key: 'geyser', docCount: 3 },
      { key: 'half_track', docCount: 3 },
      { key: 'jigsaw_puzzle', docCount: 3 },
      { key: 'lakeside', docCount: 3 },
      { key: 'refrigerator', docCount: 3 },
      { key: 'rotisserie', docCount: 3 },
      { key: 'seashore', docCount: 3 },
      { key: 'amphibian', docCount: 2 },
      { key: 'cowboy_boot', docCount: 2 },
      { key: 'crossword_puzzle', docCount: 2 },
      { key: 'leopard', docCount: 2 },
      { key: 'plastic_bag', docCount: 2 },
      { key: 'promontory', docCount: 2 },
      { key: 'scoreboard', docCount: 2 },
      { key: 'toilet_seat', docCount: 2 },
      { key: 'totem_pole', docCount: 2 },
      { key: 'window_screen', docCount: 2 },
      { key: 'American_alligator', docCount: 1 },
      { key: 'Indian_elephant', docCount: 1 },
      { key: 'Persian_cat', docCount: 1 },
      { key: 'West_Highland_white_terrier', docCount: 1 },
      { key: 'ambulance', docCount: 1 },
      { key: 'balloon', docCount: 1 },
      { key: 'ballplayer', docCount: 1 },
      { key: 'barn', docCount: 1 },
      { key: 'bib', docCount: 1 },
      { key: 'bison', docCount: 1 },
      { key: 'bottlecap', docCount: 1 },
      { key: 'bubble', docCount: 1 },
      { key: 'cannon', docCount: 1 },
      { key: 'cleaver', docCount: 1 },
      { key: 'cliff', docCount: 1 },
      { key: 'corn', docCount: 1 },
      { key: 'crutch', docCount: 1 },
      { key: 'desk', docCount: 1 },
      { key: 'digital_clock', docCount: 1 },
      { key: 'dishwasher', docCount: 1 },
      { key: 'file', docCount: 1 },
      { key: 'flagpole', docCount: 1 },
      { key: 'football_helmet', docCount: 1 },
      { key: 'fountain', docCount: 1 },
      { key: 'go-kart', docCount: 1 },
      { key: 'great_white_shark', docCount: 1 },
      { key: 'hoopskirt', docCount: 1 },
      { key: 'horse_cart', docCount: 1 },
      { key: 'killer_whale', docCount: 1 },
      { key: 'lynx', docCount: 1 },
      { key: 'macaw', docCount: 1 },
      { key: 'meerkat', docCount: 1 },
      { key: 'megalith', docCount: 1 },
      { key: 'minibus', docCount: 1 },
      { key: 'moving_van', docCount: 1 },
      { key: 'notebook', docCount: 1 },
      { key: 'ocarina', docCount: 1 },
      { key: 'oscilloscope', docCount: 1 },
      { key: 'otter', docCount: 1 },
      { key: 'overskirt', docCount: 1 },
      { key: 'oxcart', docCount: 1 },
      { key: 'parking_meter', docCount: 1 },
      { key: 'picket_fence', docCount: 1 },
      { key: 'police_van', docCount: 1 },
      { key: 'prayer_rug', docCount: 1 },
      { key: 'quilt', docCount: 1 },
      { key: 'rapeseed', docCount: 1 },
      { key: 'sandbar', docCount: 1 },
      { key: 'sarong', docCount: 1 },
      { key: 'snowmobile', docCount: 1 },
      { key: 'speedboat', docCount: 1 },
      { key: 'stretcher', docCount: 1 },
      { key: 'studio_couch', docCount: 1 },
      { key: 'stupa', docCount: 1 },
      { key: 'tailed_frog', docCount: 1 },
      { key: 'toucan', docCount: 1 },
      { key: 'trilobite', docCount: 1 },
      { key: 'unicycle', docCount: 1 },
      { key: 'vacuum', docCount: 1 },
      { key: 'vending_machine', docCount: 1 },
      { key: 'water_buffalo', docCount: 1 },
      { key: 'window_shade', docCount: 1 },
      { key: 'yurt', docCount: 1 },
    ],
  },
}

export default aggregate
