
ALTER TABLE field ADD COLUMN bool_suggest BOOLEAN NOT NULL DEFAULT 'f';

ALTER TABLE job ADD COLUMN time_pause_expired BIGINT NOT NULL DEFAULT -1;
ALTER TABLE job ADD COLUMN bool_paused BOOLEAN NOT NULL DEFAULT 'f';
