const taskScript = {
  name:
    "Crawling files in 'gs://zmlp-private-test-data/zorroa-deploy-testdata/zorroa-dev-testdata/zorroa-test-data/flowers'",
  generate: [
    {
      className: 'boonai_core.core.generators.GcsBucketGenerator',
      image: 'zmlp/plugins-core',
      args: {
        uri:
          'gs://zmlp-private-test-data/zorroa-deploy-testdata/zorroa-dev-testdata/zorroa-test-data/flowers',
      },
      module: 'standard',
      checksum: 2873964787,
    },
  ],
  execute: [
    {
      className: 'boonai_core.core.PreCacheSourceFileProcessor',
      image: 'zmlp/plugins-core',
      args: {},
      module: 'standard',
      checksum: 2178814325,
    },
    {
      className: 'boonai_core.core.FileImportProcessor',
      image: 'zmlp/plugins-core',
      args: {},
      module: 'standard',
      checksum: 117837444,
    },
    {
      className: 'boonai_core.proxy.ImageProxyProcessor',
      image: 'zmlp/plugins-core',
      args: {},
      module: 'standard',
      checksum: 457707303,
    },
    {
      className: 'boonai_core.proxy.VideoProxyProcessor',
      image: 'zmlp/plugins-core',
      args: {},
      module: 'standard',
      checksum: 482873147,
    },
    {
      className: 'boonai_analysis.zvi.ZviSimilarityProcessor',
      image: 'zmlp/plugins-analysis',
      args: {},
      module: 'standard',
      checksum: 1879445844,
    },
    {
      className: 'boonai_analysis.zvi.ZviObjectDetectionProcessor',
      image: 'zmlp/plugins-analysis',
      args: {},
      module: 'zvi-object-detection',
      checksum: 3329037091,
    },
    {
      className: 'boonai_analysis.zvi.ZviLabelDetectionProcessor',
      image: 'zmlp/plugins-analysis',
      args: {},
      module: 'zvi-label-detection',
      checksum: 2989691564,
    },
    {
      className: 'boonai_analysis.zvi.ZviOcrProcessor',
      image: 'zmlp/plugins-analysis',
      args: {},
      module: 'zvi-text-detection',
      checksum: 4290842193,
    },
  ],
  globalArgs: {},
  settings: {
    fileTypes: [
      'bmp',
      'cin',
      'dpx',
      'gif',
      'jpg',
      'jpeg',
      'exr',
      'png',
      'psd',
      'rla',
      'tif',
      'tiff',
      'pdf',
      'doc',
      'docx',
      'ppt',
      'pptx',
      'xls',
      'xlsx',
      'vdw',
      'vsd',
      'vss',
      'vst',
      'mov',
      'mp4',
      'mpg',
      'mpeg',
      'm4v',
      'webm',
      'ogv',
      'ogg',
      'mxf',
    ],
    batchSize: 20,
    index: true,
  },
}

export default taskScript
