# Generated by Django 3.1.3 on 2020-12-02 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.UUIDField()),
                ('service', models.CharField(max_length=64)),
                ('asset_id', models.UUIDField()),
                ('asset_path', models.CharField(blank=True, default='', max_length=255)),
                ('image_count', models.IntegerField(blank=True, default=0)),
                ('video_minutes', models.FloatField(blank=True, default=0.0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
