# Generated by Django 3.1.5 on 2021-01-23 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20201202_1828'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='apicall',
            unique_together={('service', 'asset_id', 'project')},
        ),
    ]
