# Generated by Django 3.2 on 2021-04-13 20:00

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20210123_0227'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='apicall',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
