# Generated by Django 3.2 on 2021-04-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_apicall_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicall',
            name='asset_id',
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='project',
            field=models.UUIDField(db_index=True),
        ),
        migrations.AlterField(
            model_name='apicall',
            name='service',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
