# Generated by Django 3.2 on 2021-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_alter_apicall_managers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='apicall',
            index=models.Index(fields=['service', 'project', 'created_date'], name='records_api_service_88d00c_idx'),
        ),
    ]
