# Generated by Django 3.2 on 2021-06-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_apicall_records_api_service_88d00c_idx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apicall',
            old_name='video_minutes',
            new_name='video_seconds',
        ),
    ]
